//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string ContactNo { get; set; }
    }
}
